<a href="https://colab.research.google.com/github/Sprusheeth/B4_PFDS_1206/blob/main/LAB2_PFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [70, 65, 80],
    [90, 88, 84],
    [60, 75, 70],
    [95, 98, 99]
])

print("Student Marks (rows=students, cols=subjects):\n", marks)

student_avg = np.mean(marks, axis=1)
student_min = np.min(marks, axis=1)
student_max = np.max(marks, axis=1)

print("\nAverage marks per student:", student_avg)
print("Minimum marks per student:", student_min)
print("Maximum marks per student:", student_max)

print("\nMarks of 3rd student:", marks[2])

above_80 = student_avg > 80
print("\nStudents with average marks > 80:\n", marks[above_80])

reshaped = marks.T
print("\nSubject-wise Performance (rows=subjects):\n", reshaped)


Student Marks (rows=students, cols=subjects):
 [[85 78 92]
 [70 65 80]
 [90 88 84]
 [60 75 70]
 [95 98 99]]

Average marks per student: [85.         71.66666667 87.33333333 68.33333333 97.33333333]
Minimum marks per student: [78 65 84 60 95]
Maximum marks per student: [92 80 90 75 99]

Marks of 3rd student: [90 88 84]

Students with average marks > 80:
 [[85 78 92]
 [90 88 84]
 [95 98 99]]

Subject-wise Performance (rows=subjects):
 [[85 70 90 60 95]
 [78 65 88 75 98]
 [92 80 84 70 99]]


In [ ]:
import pandas as pd

data = {'OrderID':[101,102,103,104,105],
        'Product':['Laptop','Phone','Tablet','Laptop','Headphones'],
        'Quantity':[1,2,3,1,4],
        'Price':[60000,25000,15000,62000,2000]}
df = pd.DataFrame(data)

df['TotalSale'] = df['Quantity'] * df['Price']

high_value = df[df['TotalSale'] > 1000]

most_sold = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False)

df['Discount'] = df['TotalSale'].apply(lambda x: x*0.10 if x>50000 else x*0.05)

df.to_excel('sales_summary.xlsx', index=False)

print("\nOriginal Data:\n", df)
print("\nOrders with Total Sale > 1000:\n", high_value)
print("\nMost Sold Products:\n", most_sold)
print("\nSummary exported to 'sales_summary.xlsx'")



Original Data:
    OrderID     Product  Quantity  Price  TotalSale  Discount
0      101      Laptop         1  60000      60000    6000.0
1      102       Phone         2  25000      50000    2500.0
2      103      Tablet         3  15000      45000    2250.0
3      104      Laptop         1  62000      62000    6200.0
4      105  Headphones         4   2000       8000     400.0

Orders with Total Sale > 1000:
    OrderID     Product  Quantity  Price  TotalSale
0      101      Laptop         1  60000      60000
1      102       Phone         2  25000      50000
2      103      Tablet         3  15000      45000
3      104      Laptop         1  62000      62000
4      105  Headphones         4   2000       8000

Most Sold Products:
 Product
Headphones    4
Tablet        3
Laptop        2
Phone         2
Name: Quantity, dtype: int64

Summary exported to 'sales_summary.xlsx'
