<a href="https://colab.research.google.com/github/Sprusheeth/B4_PFDS_1206/blob/main/LAB2_PFDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [70, 65, 80],
    [90, 88, 84],
    [60, 75, 70],
    [95, 98, 99]
])

print("Student Marks (rows=students, cols=subjects):\n", marks)

student_avg = np.mean(marks, axis=1)
student_min = np.min(marks, axis=1)
student_max = np.max(marks, axis=1)

print("\nAverage marks per student:", student_avg)
print("Minimum marks per student:", student_min)
print("Maximum marks per student:", student_max)

print("\nMarks of 3rd student:", marks[2])

above_80 = student_avg > 80
print("\nStudents with average marks > 80:\n", marks[above_80])

reshaped = marks.T
print("\nSubject-wise Performance (rows=subjects):\n", reshaped)


Student Marks (rows=students, cols=subjects):
 [[85 78 92]
 [70 65 80]
 [90 88 84]
 [60 75 70]
 [95 98 99]]

Average marks per student: [85.         71.66666667 87.33333333 68.33333333 97.33333333]
Minimum marks per student: [78 65 84 60 95]
Maximum marks per student: [92 80 90 75 99]

Marks of 3rd student: [90 88 84]

Students with average marks > 80:
 [[85 78 92]
 [90 88 84]
 [95 98 99]]

Subject-wise Performance (rows=subjects):
 [[85 70 90 60 95]
 [78 65 88 75 98]
 [92 80 84 70 99]]
