<a href="https://colab.research.google.com/github/Sprusheeth/B4_PFDS_1206/blob/main/LAB3_PFDS1206.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Addition and Subtraction
Objective:
Perform basic arithmetic operations like addition and subtraction
on 2D NumPy arrays representing matrices.

Requirements:
• Create two 3x3 NumPy arrays with random integers

• Perform element-wise addition and subtraction

• Display original matrices and results

• Use functions like np.add() and np.subtract()

• Verify operation using manual calculation for one element

• Comment on broadcasting (if used)

Deliverables:

• Python code for matrix operations

• Screenshots showing matrix inputs and results

• Short explanation of results

In [9]:
import numpy as np

matrix_a = np.random.randint(1, 11, size=(3, 3))
matrix_b = np.random.randint(1, 11, size=(3, 3))

add_result = np.add(matrix_a, matrix_b)
sub_result = np.subtract(matrix_a, matrix_b)

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nAddition Result (A + B):\n", add_result)
print("\nSubtraction Result (A - B):\n", sub_result)

row, col = 1, 2
manual_add = matrix_a[row, col] + matrix_b[row, col]
manual_sub = matrix_a[row, col] - matrix_b[row, col]

print(f"\nVerification for element ({row+1}, {col+1}):")
print(f"A[{row},{col}] = {matrix_a[row, col]}, B[{row},{col}] = {matrix_b[row, col]}")
print(f"Addition check: {manual_add} == {add_result[row, col]}")
print(f"Subtraction check: {manual_sub} == {sub_result[row, col]}")


Matrix A:
 [[ 3  2  5]
 [ 8 10  1]
 [10  1  3]]

Matrix B:
 [[ 7  6  4]
 [ 8 10  9]
 [ 4  3  7]]

Addition Result (A + B):
 [[10  8  9]
 [16 20 10]
 [14  4 10]]

Subtraction Result (A - B):
 [[-4 -4  1]
 [ 0  0 -8]
 [ 6 -2 -4]]

Verification for element (2, 3):
A[1,2] = 1, B[1,2] = 9
Addition check: 10 == 10
Subtraction check: -8 == -8


2D Matrix Multiplication (Dot Product)
Objective:
Understand and implement matrix multiplication using NumPy to
simulate applications like image transformation.
Requirements:

• Create two compatible 2D arrays (e.g., 3x2 and 2x3)

• Use np.dot() or @ operator to perform dot product

• Print intermediate and final results

• Ensure dimensions match for multiplication

• Simulate use in real-world scenario (e.g., image filters)

• Optional: Visualize matrices using matplotlib

Deliverables:

• Python script demonstrating dot product

• Output screenshots of each step

• Visualization (optional)

In [10]:
import numpy as np
import matplotlib.pyplot as plt

matrix_a = np.random.randint(1, 6, size=(3, 2))
matrix_b = np.random.randint(1, 6, size=(2, 3))

print("Matrix A (3x2):\n", matrix_a)
print("\nMatrix B (2x3):\n", matrix_b)

print(f"\nMatrix A shape: {matrix_a.shape}")
print(f"Matrix B shape: {matrix_b.shape}")
print("Dimensions match for multiplication (inner dimensions: 2)")

dot_result = np.dot(matrix_a, matrix_b)

print("\nDot Product Result (3x3):\n", dot_result)


Matrix A (3x2):
 [[3 4]
 [3 5]
 [1 3]]

Matrix B (2x3):
 [[3 2 4]
 [1 2 5]]

Matrix A shape: (3, 2)
Matrix B shape: (2, 3)
Dimensions match for multiplication (inner dimensions: 2)

Dot Product Result (3x3):
 [[13 14 32]
 [14 16 37]
 [ 6  8 19]]


**CLASSROOM EXERCISE**

In [3]:
name = input("Enter your name: ")
marks = input("Enter your marks: ")

with open("student_records.txt", "a") as file:
    file.write(f"{name},{marks}\n")

print("\nAll student records:")
with open("student_records.txt", "r") as file:
    for line in file:
        line = line.strip()
        if line:
            student_name, student_marks = line.split(",")
            print(f"Name: {student_name}, Marks: {student_marks}")

Enter your name: SPRUSHEETH
Enter your marks: 100

All student records:
Name: SPRUSHEETH, Marks: 100
